### ISSUE TITLE
Bug 10: Miniplayer just got broken

### ISSUE THREAD

**Issue by nr9992** [marverenic/Jockey#10]
Once the music player is controlled from the now playing activity, and you go back to the main activity, the miniplayer controls don't work.

**Comment by maysleazy** [comment]
Try clearing Data, worked for me after that. Plus I've seen some crashes while doing what you just said.

**Comment by nr9992** [comment]
Clearing data fixed the issue at first but later led to a couple of other bugs as well. First, once you play a song from an album, then go back to all songs and play another, it doesn't play. The player starts acting abnormally sometimes. The controls stop working, sometimes, the now playing shows that nothing is playing, even though a song is playing.

**Comment by maysleazy** [comment]
I see, happened with mine too. Probably some activity fix would do the trick. I'll see what the problem is and try to make a pull request :)

**Comment by nr9992** [comment]
Great. Keep me posted

**Comment by marverenic** [comment]
I think this is caused by a timing issue related to binding and unbinding the service -- the service has to be unbound when the app closes, otherwise the service will restart the next time music is paused. There isn't actually a callback in the API for onApplicationDestroyed, so activities bind themselves when they start and unbind when they finish.

I've reverted a few minor changes I made to the timing since m19b, so if it worked previously, then it should work again in the next release.
