### ISSUE TITLE
replace the image view in Queue list

### ISSUE THREAD

**Issue by Dirkstaal** [marverenic/Jockey#115]
Replace it with bars that animates please ?

**Comment by marverenic** [comment]
I understand that this is a behavior that several other music players have (including Google Play Music), but I don't see a benefit in changing the icon just for the sake of it. You're free to submit a PR that changes this, but I consider this to be very low priority.

**Comment by Dirkstaal** [comment]
Okay i understand :)
What about setting a .gif image as the whole background ?

**Comment by Dirkstaal** [comment]
Or keep the indicator but also highlight the current song ?

**Comment by marverenic** [comment]
I would avoid using `.gif`s in resources. They tend to be really large compared to other formats and aren't lossless. I'm also not sure if `ImageView` actually animates them by default. I'd use an [`AnimationDrawable`](https://developer.android.com/reference/android/graphics/drawable/AnimationDrawable.html) instead if possible (or maybe an animated vector drawable on API 21+).

In regards to highlighting the current song, you'll have to be a bit more specific about what you mean by that (i.e. the text color or the background color). Early versions of Jockey used to change the text color of the current song to the accent color, but I found that it provides little contrast against white backgrounds and actually makes it much harder to find the current song just by scanning the list compared to the indicator icon.

**Comment by Dirkstaal** [comment]
what i meant is keeping the indicator and highlight the text color the same
color as the indicator :)

**Comment by Dirkstaal** [comment]
Or you could make the background a bit darker or give it the accent color
of the Primary Color chosen

**Comment by marverenic** [comment]
I still don't see much of a reason to do this. The color of the indicator is the accent color, so by changing the text color to match it, you'd still run into the problem from before where the text wouldn't be legible on the background. 

Darkening the background color for this list isn't a great solution because it has ramifications on the rest of the app – both for consistency and because tablets include a slightly darker background color for the padding around the main content. Changing the list background color would affect both colors and would deviate from the material design guidelines (you'd also have to tweak this value a lot to make it work well with colors like yellow and gray).

You're more than welcome to submit a PR to change this appearance, but I don't see much of a benefit in changing this behavior.

**Comment by Dirkstaal** [comment]
Ok i understand :) 

Sorry for wasting time :p

**Comment by Dirkstaal** [comment]
You said i need to dova PR if i want it to be implimented can you please then only help me in my fork then to replace image with animated bars.. if you do not want to add it in youe repository thanks
