### ISSUE TITLE
QueueFragment updateShuffle();

### ISSUE THREAD

**Issue by Dirkstaal** [marverenic/Jockey#116]
Hi so i dont like the QueueFragment in the NowPlayingActivity 

Ive decided to remove it add it to its own fragment also changed the QueueFragment to extend DialogFragment and added it to the toolbar menu...

Now the problem is when i click the shuffle button the apk force closes and restarts ok so when i go back into the now playing the repeat is on and the queue list is correctly updated... but click the shuffle again to turn it off it force closes again... 

The queue works if i click a song or the menu ect only the update shuffle giving me problems 

Is there anything i can do ?

**Comment by marverenic** [comment]
You should try to take issues like this to a forum like StackOverflow (and include a stack trace) instead of posting them to the issue tracker since this involves modifying Jockey. If I had to guess, though, I think that you're getting a `NullPointerException` because of a particular line in `NowPlayingActivity`:

```
public class NowPlayingActivity extends BaseActivity implements ... {

    private QueueFragment queueFragment;

    ...

    private void toggleShuffle() {

        ...

        // If a QueueFragment isn't attached to the activity, this will throw a NPE:
        queueFragment.updateShuffle();
    }
}
```

Please direct any follow-up questions to the appropriate development forum.
