### ISSUE TITLE
[Question] where would i use this ?

### ISSUE THREAD

**Issue by Dirkstaal** [marverenic/Jockey#127]
I am trying to impliment a better EQ but where would i call this mEqualizer = new Equalizer(MediaPlayer.getAudioSessionId) 

I got confused with the new Media Player you implimented 

Please tell me where would i need to call it  sir ? 
Example.. class name ,, line number thanks :)

**Comment by marverenic** [comment]
Jockey already has code similar to that in `EqualizerFragment` and `MusicPlayer`. You can see what each does by running "Find usages" in Android Studio on `equalizer` and `mEqualizer` respectively.

If by "the new media player" you mean the new implementation with [ExoPlayer](https://github.com/google/ExoPlayer) in [`m/exoplayer`](https://github.com/marverenic/Jockey/tree/m/exoplayer), there's much more of an implementation hurdle. In Exoplayer, an individual instance does not have a guaranteed `audioSessionId` like a `MediaPlayer` does. Because of this, every time you start a new track, you get a new Audio Session ID (which you can't set yourself with the out-of-the-box API to my knowledge). Instead, you have to add a callback to the TrackRenderer to receive updates about the audio session ID changing and set up new `Equalizer` objects all the time. This detail is why `m/exoplayer` hasn't been merged into `master` yet – because some devices don't gracefully handle audio effects being enabled, which happens all the time in the new implementation.

**Comment by Dirkstaal** [comment]
Okay :) thanks will have a look

**Comment by Dirkstaal** [comment]
Wouldn't it be better to leave the ExoPlayer out and stick to the original Media Player ?

**Comment by marverenic** [comment]
It depends. The `MediaPlayer` class provided by the Android framework is very basic, which means that it's relatively simple to implement, but it's difficult to do more advanced things with it. It also has very bizarre implementation details including the fact that it's a very stateful object, but you can't actually tell what state it's in. This is a problem that Jockey has struggled to account for for quite a while – because whenever you try to do something in an invalid state, the player will reset completely. There are also a bunch of undocumented error codes (like -38) that just happen for seemingly no reason (and are made very difficult to debug because of the stateful and asynchronous nature of the class).

ExoPlayer is an alternative library to MediaPlayer. It exposes a very different API, and has more of an implementation cost, but it doesn't have the same problems as MediaPlayer. It's also very powerful for playing video and streaming live or static content from the internet should Jockey need to in the future.

Exoplayer 2 was recently released which has a different API that isn't backwards compatible with version 1. I haven't looked into the new API or differences between 1.0 and 2.0, but it may make it easier to implement equalizers or other audio effects.

**Comment by Dirkstaal** [comment]
Okay thanks looking forward to all the new coming updates keep up the great work what about some visualisation ?
