### ISSUE TITLE
Some Enhancement Ideas that you should look into.

### ISSUE THREAD

**Issue by Thunderbottom** [marverenic/Jockey#14]
According to me, adding these enhancements can make your application way better than it is at this moment, and for a music hog like me, these features are pretty much necessary. Please look into them IF you have time :) 

Allow the application to do/make -

* Set as Ringtone
* Allow to modify SD content (Delete, Rename Music from storage)
* Auto Created Playlist (Last Added, Last Played, Most Played, Random Songs)

**Comment by marverenic** [comment]
I'm going to close this issue since it's outdated and lists like this are hard to keep track of.

To respond to each point individually:
 - Setting a song as your ringtone seems like it could clutter the UI a bit -- I feel like people wouldn't change their ringtones that often. If you disagree, feel free to make a new issue for this.
 - Jockey has had Auto Playlists for a while per your request (although are temporarily broken in `master`. It'll be fixed before the next release).
 - I've made a separate issue (#75) for song editing since it was getting duplicated a lot.
