### ISSUE TITLE
Still has many issues. When are you fixing those?

### ISSUE THREAD

**Issue by balzathor** [marverenic/Jockey#15]
This app is so good and has a great potential, when are you fixing it?

**Comment by marverenic** [comment]
After Google I/O, I actually decided to rewrite a lot of the UI from scratch. This was partly because there were a lot of UI quirks that would be tedious to fix, but also because I wanted to use newer API's and change the view hierarchies so that I could use Google's new Design library.

Right now, I'm using the new view elements from the design libraries in place of the ones that are currently in Jockey (Namely the FAB and TabView), and I've replaced all of the ListViews and GridViews with RecyclerViews. I've also changed how the player service works so that it hopefully works properly.

I've also cleaned up a few dependencies and refactored some of the code to make it easier to work with. Right now I don't think it's ready to be released because it doesn't have all of the base functionality (mainly showing playlists or your now playing queue). Once that's been implemented again, I'll release the new version.

It might be ready as early as next week, but I don't want to promise anything yet since I'm doing a summer class, there's a [Steam Summer Sale](http://store.steampowered.com/ "Steam Homepage -- Praise Lord Gaben") going on, and my new laptop stopped working yesterday and has to be repaired. In the meantime, though, [here's a quick teaser](https://www.youtube.com/watch?v=FL9suU_YESw).

**Comment by balzathor** [comment]
Nice, that UI really looks better than what you had before! good luck with your summer classes and yeah don't waste much time playing games haha

**Comment by balzathor** [comment]
Plus, make it big this time. When you release it, make sure you add your project [Here](http://forum.xda-developers.com/android/apps-games) too. This helps you get a lot of exposure and helps you learn new things daily! I've learned coding better due to those people. You can check out my Browser Project [Here](http://forum.xda-developers.com/android/apps-games/app-ultimatebrowserproject-t3130925)

**Comment by marverenic** [comment]
Version 0.3_α-m0r0 has been uploaded
