### ISSUE TITLE
hi question about AudioSessionid

### ISSUE THREAD

**Issue by Dirkstaal** [marverenic/Jockey#151]
So previously i could've just call PlayerController.getAudioSessionId();

To get the AudiosessionId 

What do i need to do now ?

**Comment by marverenic** [comment]
As you've probably noticed, Jockey has switched to ExoPlayer for audio playback (this improves playback consistency and may allow Jockey to play music from remote sources in the future). Because of how ExoPlayer works, Audio Session IDs aren't as simple as they are with the standard `MediaPlayer` API.

ExoPlayer is backed by an `AudioTrack` to actually play media. This is not publicly exposed in the ExoPlayer API, so it's not possible to set an Audio Session ID on it. Additionally, instances of ExoPlayer aren't guaranteed to keep the same Audio Session ID throughout their lifetime.

The result of this is that you can't get Audio Session IDs in the same way as you could before. You can still call `ExoPlayer.getAudioSessionId()`, but this value could be 0, and changes all the time. If you're interested in this ID, you'll have to add a listener to ExoPlayer to listen for audio session ID changes, and then you'll have to broadcast this to the main process using an Intent or some other form of IPC. Keep in mind that IPC is expensive, so this might have noticeable latency.
