### ISSUE TITLE
Scrolling in AlertDialog Solution (Probably)

### ISSUE THREAD

**Issue by balzathor** [marverenic/Jockey#16]
For your query about having a scrollable AlertDialog [Here](https://github.com/marverenic/Jockey/blob/build/alpha/0.3/milestone0/jockey_0.3-alpha-r0m0a.txt#L7)
You can add this to your alert dialog 
`final ScrollView scrollView = new ScrollView(this); 
 scrollView.addView(layout);`

and then to the layout you may add
`<ScrollView>`
`    <LinearLayout android:orientation="vertical"`
`            android:scrollbars="vertical"`
`            android:scrollbarAlwaysDrawVerticalTrack="true">`
`        <TextView />`
`        <Button />`
`    </LinearLayout>`
`</ScrollView>`

By nesting it in `ScrollView` Container. Also, remember you cannot add `TextView` and `Button` in a `ScrollView` without having the `LinearLayout`.

**Comment by marverenic** [comment]
Lol, thanks for checking up on the project, but it's fine. AlertDialog (or at least AlertDialog in the support-v7 library) actually does do scrolling natively if you set a really long message.

There's still just a few things that need to be polished (primarily editing the queue and making shuffle and repeat work), but right now I think it'll be ready for release on Wednesday or Thursday.

**Comment by balzathor** [comment]
mhmm nice, waiting for it. I downloaded the version you uploaded yesterday to only figure out that it's just the same old release that you've uploaded. Wonder why you did that?

**Comment by marverenic** [comment]
I'm actually moving the downloads from SourceForge to GitHub because of the recent controversy about SourceForge taking over abandoned projects and updating them with installers that are bundled with a lot of potentially malicious software (let alone the download pages that are littered with ads).

While I don't believe that SF would do so to Jockey's project (or that they even *could* do that on Android), I think its reputation has changed dramatically in the past few weeks. A lot of people in the Open Source community have become very unsupportive of SF (Even one of the filter lists I use with my adblocker has completely blocked SF) and I think it's very discouraging for users to visit a site that may not be as reputable as they'd like (or even not trust at all) just to download Jockey.

Since it's just as easy for me to support downloads hosted from GitHub or SF, I'd rather migrate downloads now with the added benefit of a more seamless download when updating. The only negative side effect is that there's going to have to be a step in between 0.2 and 0.3 since all versions prior to 0.3 have a hardcoded URL pointing to the latest version on SF, but this is a one-time thing and shouldn't happen again since the new update system is much more dynamic.

**Comment by balzathor** [comment]
I agree, SourceForge has just downed its own reputation in the last few months. Fake download buttons are the thing that literally 'Grinds my gears'

**Comment by balzathor** [comment]
Try this for your newer version of Jockey, will help you with crash report. All you have to do is sign up for free and download the Fabric.io Plugin.
Crashlytics will be integrated automatically and you can get all crash reports online, and for free :)
Try it out- https://get.fabric.io/
