### ISSUE TITLE
Nice Fabric Integration, can you deploy Beta Versions?

### ISSUE THREAD

**Issue by balzathor** [marverenic/Jockey#17]
Well, Fabric allows you to deploy beta, if you don't already know that, and it would be fun to test new stuff before it comes out. 

Regards.

**Comment by marverenic** [comment]
I did see that on the dashboard and thought it was interesting, but I haven't looked into it too much (Especially since Jockey's technically in alpha right now -- I think it's weird to have a beta for an alpha version).

From now on, though, I'm going to change the way that I commit to the GitHub repo. Instead of doing huge pushes for every version, I'm going to start pushing smaller changes more frequently. Updates will still roll out as the have before, but now you'll be able to see the code before it goes live. This of course means that you can get bleeding edge builds if you compile it yourself.

If you decide you'd like to go this route, I'd just like to ask that you use Android Studio's "Run app" button instead of doing a signed release. This means that crash reports will be separated by debug and release versions in the Crashlytics dashboard and that you can install it without affecting the release version since the debug version has a different package name.
