### ISSUE TITLE
Bug playing songs

### ISSUE THREAD

**Issue by nr9992** [marverenic/Jockey#22]
I downloaded the zip from github and set it up in my android studio. Had to comment out the crashlytics section because I don't have a crashlytics key. 

Now what is happening is that when I click on a song in the all songs tab, no song plays. There is no queue added to the now playing as well. But if I click on the song from the artist or album page, it plays.

To try digging into the issue, I simply added a toast to register the onClick event. Turns out that the viewholder on the songs tab is not registering the click events as no toast is shown, whereas in the song list under artist or album page, clicking the song fires up the toast confirming the onClick call.

Do you have any clue what is wrong? Please look into it. I'm trying to do the same

**Comment by marverenic** [comment]
Apparently this has been broken for almost a week and I didn't notice. It looks like it was broken in df1097b by removing [a single line](https://github.com/marverenic/Jockey/blob/c5b58ecbd26c354aa1d1bb6751514bd8a41b7979/app/src/main/java/com/marverenic/music/fragments/SongFragment.java#L45).

It should be resolved as of b30a039 and I've moved SongViewHolder.setSongList() to its constructor to avoid this in the future (which is why the commit has a lot more than one line).
