### ISSUE TITLE
Notification reappear randomly

### ISSUE THREAD

**Issue by Khang-NT** [marverenic/Jockey#224]
The notification always reappears after "notification sound of another app triggered", related to https://github.com/marverenic/Jockey/issues/107.  It happen with both KITKAT and N device, so whenever audio focus changed, `PlayerService` will show the player notification.

I'm reading your _PlayerService.java_ and _MusicPlayer.java_, it has pretty documentation, so hope I understand correct. When `onAudioFocusChange`:
```java
/* MusicPlayer */
        switch (focusChange) {
            case AudioManager.AUDIOFOCUS_LOSS:
                // ...
                pause();
                break;
            case AudioManager.AUDIOFOCUS_LOSS_TRANSIENT:
                // ...
                pause();
                break;
            case AudioManager.AUDIOFOCUS_GAIN:
                // ...
                if (mResumeOnFocusGain) play();
                break;
        }
        // updateNowPlaying(); this line is duplicated while calling `pause()` and `play()` (above)
        // is already triggered it if the player state changed.
        // moreover, if player is pausing -> focus loss -> still pausing -> no need to call it
        updateUi();

/* PlayerService */
private void showNotification(Notification notification) {
        if (mBeQuiet && !musicPlayer.isPlaying()) {
            return;
        }
        /* Should we check if notification is "deleted"
        if ((mBeQuiet || mStopped)   
              && !musicPlayer.isPlaying()) return;
        */
}
```

And I have a question in `PlayerService`, why we need to `START_STICKY`?  It should be stop completely  when the player isn't playing (except when service is being bound), and why you don't kill service process while UI process is running??

Thanks for awesome project.

**Comment by marverenic** [comment]
Thanks for pointing this out. I've gone ahead and opened a PR with this change (#225).

As for your other questions, `START_STICKY` is used to make sure that Android doesn't kill our service process (or if it does, it tells Android to restart it). This doesn't happen on newer versions of Android, but on Lollipop, moving the service to the background and then closing the app actually causes Android to kill the service. Without this flag, the service could not run on L devices without the app in the recent apps list.

The service staying running while the app is open was mostly a design decision. It was easier to build at the time (since the app only needed to start the service once and then assume it never stopped running), and there's a pretty good chance that even if the user dismisses the notification while the app is running they may still decide to play music without closing the app. Because the time it takes to start the service may be somewhat long on certain devices, and because there isn't too much overhead to keep the service running while the app is running, it's normally a good idea to just keep the service running until the app closes instead of having to worry about killing and restarting the service.
