### ISSUE TITLE
Change  package name

### ISSUE THREAD

**Issue by AKprisonER** [marverenic/Jockey#248]
I done refactoring .But none reflects correctly.
Whats the reason?
Is it becoz of external libraries?
i had done so many  refactoring for other apps, But jockey app contains so much things inside.
Is there anyone who refactored ,changed package name succesfully?

**Comment by AKprisonER** [comment]
Refactoring results in so many conflicts in AIDL

**Comment by marverenic** [comment]
I know there have been a couple of people who changed the Android package name (which is pretty easy to do – you just need to change the package name in the `AndroidManifest.xml` and all the declared paths to be accurate). I'm not sure if anyone has changed the Java package. Doing a refactor in Android Studio should have done most of the work, but you'll probably need to do a clean recompile to get Dagger working.

For the AIDL files, I don't think that Android Studio will modify them at all when doing a Java refactor. You'll have to go into the AIDL folder (`app/src/main/aidl/...`) manually and make sure the package structure and `package` declarations match the ones you changed in Java.

**Comment by AKprisonER** [comment]
issues continues.Refactoring in not working fine.
And modifying packhae and structure in AIDL file shows errors related to AIDL.exe
Can you plz try a sample refactoring?

**Comment by marverenic** [comment]
I just attempted a refactor in Android Studio to rename `com.marverenic.music` to `com.marverenic.jockey`. I was able to get the project to successfully compile in the end, but there were a couple of things that were not automatically refactored correctly.

The first thing that I had to do was to fix the `package` and `import` statements in the AIDL files. To do this, you'll need to open every `.aidl` file and make sure that all `package` statements and `import` statements are pointing to the correct package after your refactor. I suspect this is what's causing your AIDL errors.

I also had to change the `activity_library_base_wrapper.xml` layout since the `NestedCoordinatorLayout` view had its package renamed, but the xml file was not automatically updated.

**Comment by Lv-aki** [comment]
i tried com.marverenic.jockey to com.marveren.jockey ,Fixing those refactoring thing is looking so difficult.
Will update the error logs

**Comment by marverenic** [comment]
I'm gonna close this due to inactivity. Feel free to reopen this or start a new issue if you're still having problems with this.

**Comment by AdebiyiPaul** [comment]
You mean all that needed to be changed is the package in AndroidManifest and import in all .aidl files?

**Comment by Parlegrandpa** [comment]
Please give complete description of how i can change the package name, i'm getting lot of errors trying to change it here

**Comment by Parlegrandpa** [comment]
@marverenic Kindly explain this line 

> **"I also had to change the activity_library_base_wrapper.xml layout since the NestedCoordinatorLayout view had its package renamed, but the xml file was not automatically updated."**

because after building the project, i got the error below

Information:Gradle tasks [clean, :app:generateDemoDebugSources, :app:prepareDemoDebugUnitTestDependencies, :app:mockableAndroidJar, :app:generateDemoDebugAndroidTestSources, :app:compileDemoDebugSources, :app:compileDemoDebugUnitTestSources, :app:compileDemoDebugAndroidTestSources, :exoplayer-flac:generateDebugSources, :exoplayer-flac:mockableAndroidJar, :exoplayer-flac:prepareDebugUnitTestDependencies, :exoplayer-flac:generateDebugAndroidTestSources, :exoplayer-flac:compileDebugSources, :exoplayer-flac:compileDebugUnitTestSources, :exoplayer-flac:compileDebugAndroidTestSources, :seekarc:generateDebugSources, :seekarc:mockableAndroidJar, :seekarc:prepareDebugUnitTestDependencies, :seekarc:generateDebugAndroidTestSources, :seekarc:compileDebugSources, :seekarc:compileDebugUnitTestSources, :seekarc:compileDebugAndroidTestSources]
C:\Users\PAD-PC\Documents\Android Projects\Tutorials\Jockey-master\Jockey-master\app\build\generated\source\apt\demo\debug\com\marverenic\musicplus\databinding\ActivityLibraryBaseWrapperBindingImpl.java
Error:(14, 44) error: package com.marverenic.music.view does not exist
C:\Users\PAD-PC\Documents\Android Projects\Tutorials\Jockey-master\Jockey-master\app\build\generated\source\apt\demo\debug\com\marverenic\musicplus\databinding\ActivityLibraryBaseWrapperBindingLandImpl.java
Error:(14, 44) error: package com.marverenic.music.view does not exist
Error:Execution failed for task ':app:compileDemoDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
Information:Total time: 14 mins 53.264 secs
Information:3 errors
Information:0 warnings
Information:See complete output in console

**Comment by marverenic** [comment]
You should be able to rename the package using the following steps:
1. Use the Rename refactor tool to rename `marverenic` to your desired package name
2. Update all aidl files and directories to replace `marverenic` with the new package name
3. Open `src/res/layout/activity_library_base_wrapper.xml` and update the `com.marverenic.music.view.NestedCoordinatorLayout` with the appropriate fully-qualified package name
4. Clean and rebuild the project

**Comment by AdebiyiPaul** [comment]
Thank you very much. It's resolved
