### ISSUE TITLE
about vector usage in this project

### ISSUE THREAD

**Issue by androrz** [marverenic/Jockey#268]
Hey, I was forking this repository and want to add AnimatedVectorDrawable feature, bus AndroidStudio prompt that <animated-vector> requires API level 21 (current min is 16), I googled about that, it says 

> As of Android 5.0 (API level 21), there are two classes that support vector graphics as a drawable resource: VectorDrawable and AnimatedVectorDrawable.

This means vector drawable and animated vector drawable was unavailable pre API level 21, unless use suport library like this: 
```
//For Gradle Plugin 2.0+
 android {
   defaultConfig {
     vectorDrawables.useSupportLibrary = true
    }
 }
```
I did't find any declaration in build.gradle in the project like this ,  but you can still use vector drawables without any problem,  and AndroidStudio did't give any error prompt.  On the other way ,  if I add `vectorDrawables.useSupportLibrary = true` declaration like above, and use  app:srcCompat attribute instead of android:src，the app still crash for the reason of having using vector drawables in system notifications.
What's the trick?

**Comment by marverenic** [comment]
I actually haven't looked into using AnimatedVectorDrawables yet. I know that newer versions of Android Studio and the Gradle plugins will automatically generate .png's for every vector drawable that's declared so that they can be used on pre-L devices, but I don't think it can do the same thing for animated vectors.

I think that the support libraries used to offer an appcompat implementation, but I believe it was removed because of performance issues. You may be able to find a third party library that can do this, though. Alternatively, you could just only perform the vector animations on Lollipop and higher devices (which nowadays is 70% of all active devices), or just use more old-fashion animation techniques.

Let me know if you're able to get this working, since I'm a bit curious myself.

**Comment by androrz** [comment]
Yes, just as you say, newer versions of AS and gradle plugins will automatically pngs for vector drawable but I think the automatic generation was disabled if we declare to use support library `vectorDrawables.useSupportLibrary = true`
Maybe I should try some alternative methods. Thanks！
