### ISSUE TITLE
Release a build after every update

### ISSUE THREAD

**Issue by balzathor** [marverenic/Jockey#27]
So we can test it and report asap.

Regards.

**Comment by marverenic** [comment]
RC1 is up now. I'll try to do more frequent updates in the future with beta testing and possibly through Google Play, but for now the latest version has the same code as my computer.

Thanks again for testing, and let me know if you find something that needs to be addressed, otherwise I'm planning to remove the pre-release tag really soon.

**Comment by marverenic** [comment]
Jockey 1.1.0 beta 0 is currently available on GitHub and Google Play Beta Testing (which is significantly easier to update and will allow for more frequent beta updates). You can opt-in to the open beta [here](https://play.google.com/apps/testing/com.marverenic.music), or continue to sideload new versions as before.

**Comment by balzathor** [comment]
You should start a G+ community to get testers to test your app, also make a [trello](https://trello.com/) page for this application so users can share new features and experiences based on the application.

**Comment by IzzySoft** [comment]
Is there any reason why you've stopped attaching the `.apk` files to the `releases/`? The last one was around v1.2, but not even the (stable) v2.1.1 has an `.apk` attached anymore. Maybe you could fill that gap again? Thanks in advance!

**Comment by marverenic** [comment]
Done. The previous versions had a simple built-in update mechanism, so this was a straightforward way of deprecating that after the switch to Google Play. I went ahead and uploaded all of the APK's that were on the Play Store for archival purposes.

**Comment by Thunderbottom** [comment]
Do you want me to setup travis for you? I can try to do that. It'll have a build up for every commit on `master`

**Comment by marverenic** [comment]
I like the idea, but I think there might be a few complications. The first one is that each build should get an incremented version ID to differentiate between builds, and I don't think that Travis is capable of doing this. I'd also like for these builds to have Crashlytics enabled, if possible, but I don't know if there's a way to do it without publishing the API key. Similarly, it looks like Travis provides a lot of options for deploying builds, but it looks like most of them require putting OAuth tokens, API keys, or even plain-text passwords in the travis.yml file.

**Comment by IzzySoft** [comment]
I think adding an `.apk` *for each build* is a bit overdoing it. There should be one *for each tag,* though – at least for the most recent one 😸

**Comment by Thunderbottom** [comment]
@marverenic : I'll look into it tonight. If it is possible, I'll start working on it.

@IzzySoft : You can have builds for each tags if you want, instead of every commit.

**Comment by IzzySoft** [comment]
@Thunderbottom Of course the decision is made by @marverenic – but I'd guess he'd agree on that. A build for each commit would just drive the `versionCode` up unnecessarily, and might not even be needed. Only few will want to update that frequently (sure, testers might occasionally – but I doubt that would justify it). Have it automated for each tag OTOH would be very useful – even more if it could also automatically attach the resulting `.apk` to that tag, saving @marverenic some extra work 😺

**Comment by marverenic** [comment]
I'd rather manually upload the apk for each release tag to be honest. It doesn't really add any additional work at all since I already need to build and upload the apk to the Play Store, and I'd rather make sure that the build on Github is exactly the same as the one on the Play Store (the main difference I'd be concerned about is that Proguard could perform a different obfuscation on each build, which means the apk's would have different deobfuscation mappings).
