### ISSUE TITLE
v.1.1.0 Beta 2, Skip Previous still not fixed

### ISSUE THREAD

**Issue by balzathor** [marverenic/Jockey#29]
You can still see it for yourself

![Glitch](https://cloud.githubusercontent.com/assets/11243138/10964480/5b0e7016-83cd-11e5-8b34-1a0fdac6b94a.png)

**Comment by marverenic** [comment]
That's odd, it looks fine in the emulator. I've made a slight change to the xml file for that icon, but I don't want to commit it unless I know it works. I've compiled a debug build that has a few very minor code optimizations in addition to the change I mentioned before which you can download [here](dl.dropbox.com/u/5187757/jockey_1.1.0-b2-possibly-fixed.apk). You can install it like a normal apk, but it won't overwrite your current installation since it has a different package name.

Let me know if this fixes it for you, and thanks again for testing.

**Comment by balzathor** [comment]
Alright I'll give it a try and report when I get time :) :+1:

**Comment by marverenic** [comment]
I added a potential fix with 49813a9. It's not the same one as in the apk I linked to before, but it should still work (probably). The patch has rolled out in 1.1.0 beta 3, so I've taken down the link I sent before.

Let me know if this resolves it when you have the time.

**Comment by balzathor** [comment]
The debug version had the bug fixed.
