### ISSUE TITLE
Equalizer doesn't work

### ISSUE THREAD

**Issue by nr9992** [marverenic/Jockey#30]
Equalizer doesn't work on my device. It works in other music players, creating a difference in how the song sounds, but the equalizer here creates no difference whatsoever.

This is exactly what happened when I tried to add the equalizer to Jockey earlier. It didn't work somehow.
Please look into this

**Comment by marverenic** [comment]
What device are you using?

**Comment by nr9992** [comment]
Moto G 1st gen.

On Sun 8 Nov, 2015 2:57 am Andrew Bailey <notifications@github.com> wrote:

> What device are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marverenic/Jockey/issues/30#issuecomment-154753137>.
>
-- 

- Neel Raj

**Comment by marverenic** [comment]
I've heard that Motorola has some issues with the AudioEffects API's that are built into Android. When enabling the equalizer at the start of a music session on my Moto X (2nd gen) for example, the volume will sometimes briefly pop to a high volume even if the phone is muted. (One of my friends reported the same problem on a much older Motorola phone)

If your phone has Motorola's Audio Effects panel installed, the equalizer option should redirect to it by default. Disabling this application doesn't affect the behavior of Jockey's equalizer. The long-press override for the built-in equalizer is considered somewhat unstable on devices that ship with OEM implementations of the equalizer (which is why a note appears below the sliders if a system equalizer is detected).

**Comment by nr9992** [comment]
Yes. Disabling the Motorola Audio effects did make the equalizer work but
now the usual music player Phonograph that I use can't access it as it uses
the audiofx engine and has no implementation of its own. I do want to point
out that Phonograph works perfectly with Moto's audiofx engine as it does
with others. So we still need a better implementation here

On Sun 8 Nov, 2015 3:42 am Andrew Bailey <notifications@github.com> wrote:

> I've heard that Motorola has some issues with the AudioEffects API's that
> are built into Android. When enabling the equalizer at the start of a music
> session on my Moto X (2nd gen) for example, the volume will sometimes
> briefly pop to a high volume even if the phone is muted. (One of my friends
> reported the same problem on a much older Motorola phone)
>
> If your phone has Motorola's Audio Effects panel installed, the equalizer
> option should redirect to it by default. Disabling this application doesn't
> affect the behavior of Jockey's equalizer. The long-press override for the
> built-in equalizer is considered somewhat unstable on devices that ship
> with OEM implementations of the equalizer (which is why a note appears
> below the sliders if a system equalizer is detected).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marverenic/Jockey/issues/30#issuecomment-154757583>.
>
-- 

- Neel Raj

**Comment by marverenic** [comment]
Oh, I see what you mean. I thought it worked with the system equalizer, but something must have changed that. I'll look into it

**Comment by nr9992** [comment]
What you could do right now, however is to not access the system audio fx
panel at all and use Jockey's equalizer for every device.

On Sun 8 Nov, 2015 3:54 am Andrew Bailey <notifications@github.com> wrote:

> Oh, I see what you mean. I thought it worked with the system equalizer,
> but something must have changed that. I'll look into it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marverenic/Jockey/issues/30#issuecomment-154758165>.
>
-- 

- Neel Raj

**Comment by marverenic** [comment]
As of 7334164, the equalizer setting no longer links to the system equalizer and the built-in equalizer is always used.

Although the commit message suggests otherwise, the lingering problem with the Moto X loudness spike is still present, so I'll have to keep looking into possible solutions. If you have a minute, do you mind letting me know if the Moto G shows any issues when the equalizer is enabled?

**Comment by marverenic** [comment]
Thanks to [Apollo](https://github.com/adneal/Apollo-CM), I've figured out why the system audio effects panel never affected playback (You have to broadcast an [AudioEffect.ACTION_OPEN_AUDIO_EFFECT_CONTROL_SESSION](http://developer.android.com/reference/android/media/audiofx/AudioEffect.html#ACTION_OPEN_AUDIO_EFFECT_CONTROL_SESSION) intent).

Since the system equalizer now works correctly, I've reverted most of the changes in 7334164 as of 3c46dc5 in favor of linking to the built-in equalizer if one is available to avoid device-specific bugs. The previous behavior of long-pressing for the built-in EQ is still available, but as before it's not recommended to use if your device ships with a global EQ.
