### ISSUE TITLE
No songs, artists, or album displayed

### ISSUE THREAD

**Issue by AdebiyiPaul** [marverenic/Jockey#314]
Hi
I just downloaded this wonderful project. Kudos to the author and contributors.

As I built and installed the project on my phone, nothing was returned I.e songs, artists, genres and albums fragments are blank. Is there something I need to do?

**Comment by marverenic** [comment]
It sounds like Android Studio may have defaulted to the demo version of Jockey, which tries to load a fake library instead of your actual music library. You should be able to fix this by changing the build variant from `demoDebug` to `standardDebug` (This option should be in the "Build Variants" tab in the bottom left corner of Android Studio).

**Comment by AdebiyiPaul** [comment]
Oh! Really? Thanks for your quick response.
