### ISSUE TITLE
Register the app as amusic player in android

### ISSUE THREAD

**Issue by oliver92** [marverenic/Jockey#347]
The app does not register its self as a music player in android. You can see this in the Android Auto app. You cannot choose the app as a source for music.

**Comment by oliver92** [comment]
I meant Automate not Android Auto :)

**Comment by oliver92** [comment]
Ok so apparently Automate does not auto detect  music players but they add support for them manually. You can close the issue. Sorry for the inconvenience.

**Comment by marverenic** [comment]
I went ahead and tried out the app since I wasn't familiar with it, and I was able to get it working with Jockey. I'm not sure which action you're trying to perform, but try the following settings:

![screenshot_20180302-173622](https://user-images.githubusercontent.com/10948413/36925332-6ca79fea-1e40-11e8-9307-78ebc0fc4668.png)

I'm going to close this issue since Jockey isn't really designed around automation like this, but I'm open to the idea of making a system-wide API for Jockey if there's a generic use case that can be implemented well.

**Comment by oliver92** [comment]
I was actually talking about a car dashboard app called Automate haha. Turns out there's another app called the same name. The one u tried :)

Heres the playstore link:

https://play.google.com/store/apps/details?id=com.bitspice.automate

**Comment by marverenic** [comment]
Oh, yeah, I see what you mean. It doesn't look like they have an API and aren't using the platform standard integrations. So I think media player integration is all up to them.
