### ISSUE TITLE
add thumbnail to music lists

### ISSUE THREAD

**Issue by gharibeh** [marverenic/Jockey#352]
it will be good if you add thumbnails to song lists, album lists, and etc.
it will help users to find songs faster

**Comment by marverenic** [comment]
I'm not sure if I agree with the premise of helping find songs faster. Because album artwork isn't unique to particular songs, it's not an identifier for the user to scan when scrolling through tracks. Humans are simply better at quickly searching lists of alphabetically sorted text than they are at identifying thumbnails – especially given how small the thumbnails would have to be.

I just don't think it's worth sacrificing the memory usage, performance, and screen real estate for something that ends up being purely aesthetic (and subjective at that).

**Comment by gharibeh** [comment]
You are right about performance stuff but this is a feature which most of the players has it these days, and this fantastic player seems incomplete without it. At last, you can add an element to the app which user can enable or disable showing thumbnails in their list using it.
