### ISSUE TITLE
Affix of search lyric,headset bluetooth and  Karaoke feature into jockey app

### ISSUE THREAD

**Issue by dzamizain** [marverenic/Jockey#367]
Components

   Jockey is a easy music player that based at Google's Material Design standards. This music player designed more simple and lightweight with features designed for music enthusiasts and casual listeners alike.The feature of this app is like Customizable interface with 81 color combinations to choose from and then ,Last.fm integration for retrieving artist images and descriptions,Smart Playlists with fully customizable rules,Custom equalizers,Gapless playback,Home screen widgets
And of course, every feature you'd expect from a music player including playlist editing, lockscreen controls and artwork, and fluid navigation between all of your content

 Proposal
 after use the application in a few days without find features interesting.I think there are some features incomplete on jockey music player and must be implemented inside so the other users can feel the new sensations.and as the PO specified he might want to enhance the application, so I like to share my idea 
Into this app for implemented following feature.
 1.search lyric
 Search feature is a feature that use to find the lyric or the sentence of the song.
 2.headset bluetooth
 When this feature activated The users could hear the music in their headset bluetooth with wireless cable.
 3.feature karaoke
 Sing the music with my own voice is a new sensation and will delightful.
  actually I love to see more changes on the UI, including all the more intriguing features and I think will make it more user-friendly when using.

 Mocks up
Pictorial illustration of my idea into this app
 Image below shows the lyric feature has been implemented and ready to typing search for the lyric of the song.

![PicsArt_07-27-09.10.32.jpg](https://cdn.steemitimages.com/DQmQNmQiTpYSFV4iVzbDcaR3mUapQAdz2WVBHLEAhWxvtYS/PicsArt_07-27-09.10.32.jpg)
 Picture below show how headset bluetooth feature can be implemented.![PicsArt_07-27-09.19.28.jpg](https://cdn.steemitimages.com/DQmSpioyGG62aNmki7ocfwbXWJvhHBSwHU96fFsPoau62ud/PicsArt_07-27-09.19.28.jpg)
 Image below the karaoke feature has been created.
![PicsArt_07-27-09.23.23.jpg](https://cdn.steemitimages.com/DQmYkK3YTMN4ucSyiawJmgwJSJYDmLuHerfhDT446DoQdQ2/PicsArt_07-27-09.23.23.jpg)

 Benefit
1. search lyric
 The listener is needs the lyric of music so they're could understood clearly sentence by sentence of music they hear.the lyrics serve to create an atmosphere and imaginary imagery to the listener and create diverse meanings.

2.Play via bluetooth
  listen to music with hands free or called using wireless headset,this going to be pleasant when walking,sitting or another activity with listen to music.and hear music with no connection cable are good when traveling,touring or any journey.this is best Idea for implemented this feature.

3.karaoke
 One last is karaoke feature that will give a good sensation for the listener to enjoy the song, so much of pressure on anybody brain after the activity and I would think singing karaoke will quick fix to calm down their brain.releasing stress in mind is the benefits of karaoke.
 In another side the benefits of karaoke is for practice singing of music for everybody who want to be a singer.

**Comment by marverenic** [comment]
Thanks for the feedback! In the future, please make sure to keep issues focused on one specific topic. Otherwise it gets difficult to keep track of progress on individual tickets. See below for my comments on each issue.

Unfortunately, there is nothing I can do to implement these features, as they range from being already implemented to being virtually impossible to implement at this time. As such, I'm going to close this issue, but please feel free to open a separate issue if you'd like to follow-up on on anything specific.

## Lyric search
This is just a matter of finding an API. Unfortunately, I'm unaware of a free lyrics API appropriate for the project. Most of the ones that I've found either are a paid service, are deprecated/unsupported/unstable, or are SOAP instead of of REST APIs. Let me know if you can find a more appropriate API.

## Bluetooth playback
Jockey already supports playback over Bluetooth. Just connect a Bluetooth headset and Android will route all media playback from Jockey to the headset. Controls on the device will also work (if it has a play/pause button, for example). If you're listening to music in your Bluetooth-enabled car, then you'll also see metadata about the current song if the infotainment unit supports it. Let me know if you're running into specific issues by opening a new issue, but no additional UI or setup in the app is required to play music over Bluetooth.

## Karaoke
I'm assuming that you mean you want to listen to music with vocals filtered out, right? There are two potential implementations for this that I can think of, but both have enormous drawbacks. I've detailed them below, but let me know if you have other implementation ideas.

### Build an audio filter that strips vocals
This entails doing signal processing on audio to filter out frequencies that match human voices. There are a number of filters and algorithms that exist to do this, but they are generally not very accurate and are infeasible to implement given the scope of this project.

The implementation of such a filter would involve a significant amount of digital signal processing. Jockey does not currently do anything along these lines, and such an implementation would use a significant amount of power (since such processing is happening in software), and would need to be implemented with sophisticated algorithms in native code. Using native code in this way is error-prone, outside the scope of the application, and would lead to Jockey's application binary using significantly more space on your phone's storage.

Using more common algorithms for this also doesn't leave a high quality result, which [someone else explains much better than I can](https://www.youtube.com/watch?v=vn1KQb5kVY8). There are more advanced algorithms that achieve this, but there is an inordinate amount of research and money involved in developing these, and they often require human intervention to achieve a final result.

### Implement an online search for instrumental versions of songs
More simply, Jockey could simply perform a web search for "[name of song] instrumental." This may yield decent results for more popular songs, but requires that music has valid metadata and won't work at all for more obscure bands. Considering that this is something that a user can trivially do on their own and that the results will be hit-or-miss, I think it would do more harm than good to include this implementation – otherwise it gives users a significantly higher expectation than what we know can be delivered.
