### ISSUE TITLE
Additional theme options

### ISSUE THREAD

**Issue by cyalins** [marverenic/Jockey#38]
Would you consider adding more complex theme options, similar to some other music players? Some of the presets don't seem that appealing to me, and it'd be great if there was more variety

**Comment by nr9992** [comment]
I forked the repo a couple weeks back and have been working on integrating a more comprehensive theme engine in Jockey that would provide you with unlimited theming options like some other popular players out there. Would take a little time to replace the existing theme setup with the new one. Stay tuned

Neel Raj

**Comment by marverenic** [comment]
The current implementation of themes requires that every available combination of accent and primary colors is hard-coded, but now that AppCompat has a Day Night theme it's much easier to add new themes since there doesn't need to be a light and dark version of each combination.

What options would you like to see? To keep the current implementation with 7 primary colors and 7 accents, there would have to be 7<sup>2</sup> = 49 Theme definitions (up from the current 7) to be able to choose any combination of primary and accent colors. To have all 17-20 colors (depending on which you include) in the [Material Design color palette](https://www.google.com/design/spec/style/color.html#color-color-palette), this number jumps to 289 or 400. I'm sure that there's a better way of doing this at runtime, but I haven't found a comprehensive library for this and Jockey currently uses a lot of ?attr properties which are read from the current Theme and can't be modified at runtime.

If you're only interested in having one or two alternate versions of themes where the accent color is is a complementary color of the primary color, this would be much easier to implement. If this sounds good, feel free to suggest some combinations using a site like https://www.materialpalette.com/ or similar.

**Comment by nr9992** [comment]
I have a way to do that. I'm working on it
On Tue, 1 Mar 2016 at 1:34 AM, Andrew Bailey <notifications@github.com>
wrote:

> The current implementation of themes requires that every available
> combination of accent and primary colors is hard-coded, but now that
> AppCompat has a Day Night theme it's much easier to add new themes since
> there doesn't need to be a light and dark version of each combination.
>
> What options would you like to see? To keep the current implementation
> with 7 primary colors and 7 accents, there would have to be 72 = 49 Theme
> definitions (up from the current 7) to be able to choose any combination of
> primary and accent colors. To have all 17-20 colors (depending on which you
> include) in the Material Design color palette
> <https://www.google.com/design/spec/style/color.html#color-color-palette>,
> this number jumps to 289 or 400. I'm sure that there's a better way of
> doing this at runtime, but I haven't found a comprehensive library for this
> and Jockey currently uses a lot of ?attr properties which are read from the
> current Theme and can't be modified at runtime.
>
> If you're only interested in having one or two alternate versions of
> themes where the accent color is is a complementary color of the primary
> color, this would be much easier to implement. If this sounds good, feel
> free to suggest some combinations using a site like
> https://www.materialpalette.com/ or similar.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marverenic/Jockey/issues/38#issuecomment-190359317>.
>
-- 

- Neel Raj
