### ISSUE TITLE
Few suggestions for better ui and performance

### ISSUE THREAD

**Issue by salvator91** [marverenic/Jockey#41]
- Hide the miniplayer footer when nothing is playing. It looks better than an empty footer.

- If possible add an animated playpause button..there are several on github..

- If possible try to replace the current NowPlayingActivity with sliding panel layout. Most of the new music players use that layout. looks and feels great. No hurry though..Yours is good too..

- add missing album art from lastfm. u may need jaudiotagger

- add a sleeptimer

- add widgets. This is a must. :-) ..Please have a look at apollo for help with code.
https://github.com/CyanogenMod/android_packages_apps_Apollo/tree/cm-11.0/src/com/andrew/apollo/appwidgets

**Comment by marverenic** [comment]
I've moved this issue into several smaller ones since it's hard to keep track of lists of feature requests like this one. See:
 - #70: Hide the now playing footer when nothing is playing
 - #71: Make the now playing footer behave like a sliding panel
 - #72: Retrieve missing album artwork from Last.fm
 - #73: Add a sleep timer to stop playback at a specified time
 - #74: Add launcher widgets to control music playback
