### ISSUE TITLE
the keyboard will close where native listened the event from html

### ISSUE THREAD

**Issue by xinqing** [marverenic/Jockey#45]
when the input box changed content，I send a event from html and listen in native. In this scene the keyboard automatically shut down，This is not what I want. do you know why?

**Comment by marverenic** [comment]
Sorry this took so long to respond to, but I don't understand what you're asking.

Jockey only has text fields in a few places including the fields in `AutoPlaylistEditActivity`, and the search bar in `LibraryActivity` and `SearchActivity`. None of these Activities use HTML at all, and I don't understand what you mean by listening in native since Jockey has no native C code.

I'm going to close this issue, but let me know if there's anything else I can answer.
