### ISSUE TITLE
Are you planning to make Jockey compatible with Android 4.0?

### ISSUE THREAD

**Issue by DrGosh** [marverenic/Jockey#5]
Hi, marverenic:) I really love your player, but i have android 4.0 and i can't use Jockey:(( Can you make Jockey work on API15(Android 4.0)? Thanks in advance, your app is gorgeous

**Comment by marverenic** [comment]
I don't remember what in particular made 4.1 the minimum version, but I think there were a few API's related to media, notifications, and some methods I used for theming from Jelly Bean that pushed API 16 to become the minimum. It's also a bit hard to justify building apps for ICS because its emulator performance is worse than more recent versions and since it has [less than 6% market share] -- even [Google has stopped releasing Chrome updates for ICS].

After a bit of tweaking, however (mostly to the notification and player), I've gotten Jockey to run in a 4.0.3 (API 15) emulator. There are still a lot of loose ends related to UI, but as a music player it's mostly functional. You can probably expect milestone 19 to run (or at least install) on 4.0.3+, but more than likely it will be full of exciting problems for a while.

[less than 6% market share]:https://developer.android.com/about/dashboards/index.html
[Google has stopped releasing Chrome updates for ICS]:http://blog.chromium.org/2015/03/freezing-chrome-for-ice-cream-sandwich_3.html

**Comment by marverenic** [comment]
Starting with version 0.3, Jockey no longer supports Android ICS. Compatibility may be reconsidered in the future, but for now I'd like to spend more time on features and polish than on compatibility.

**Comment by balzathor** [comment]
You can't, basically most of the stuff support API 16+ ONLY now, because there's a few things that have been improved, or rather optimized that you won't want to or can't use on ICS. As far as I know, ICS support on everything has been long dropped off now.
