### ISSUE TITLE
Resume playback when headset plugged back in

### ISSUE THREAD

**Issue by shkschneider** [marverenic/Jockey#51]
This is currently the only feature I miss to make this app my Music app.
Shuffle music player does it, Power AMP also, Phonograph does not, nor Jockey.
I really wish it had that feature.

Technical: this should help http://stackoverflow.com/a/13610712 related to https://developer.android.com/reference/android/content/Intent.html#ACTION_HEADSET_PLUG in https://github.com/marverenic/Jockey/blob/master/app/src/main/java/com/marverenic/music/player/PlayerService.java maybe?

**Comment by marverenic** [comment]
To clarify, should playback start every time headphones are plugged in, when AudioFocus is being held by Jockey, or only after headphones are unplugged and reconnected?

**Comment by shkschneider** [comment]
I just would like Jockey to resume playback as long as the notification is there, averytime I replug the headset. If the service is dead or the notification got cancelled, I totally understand (and somehow expect) Jockey NOT to resume playback.

**Comment by salvator91** [comment]
I think there should be an option for users to avail this. Otherwise it would be annoying if music starts playing everytime you plug in the headset.

**Comment by shkschneider** [comment]
Of course it would need to be optional.

**Comment by shkschneider** [comment]
The new Awareness API could surely help:
https://developers.google.com/awareness/android-api/snapshot-get-data#get_headphone_state

Your app can be notified when headphones are plugged/un-plugged:
https://developers.google.com/awareness/android-api/fence-api-overview

**Comment by marverenic** [comment]
Thanks for the link, but I don't think that the Awareness API is a good solution here. I say that because it involves adding Google Play Services as a dependency, and doesn't substantially clean up the implementation details. Because `MusicPlayer` already has a BroadcastReceiver listening for headphone connection changes, it makes much more sense to just add another branch to its if-else statement to see if headphones were connected, and handle it as described before.
