### ISSUE TITLE
Music takes 1 second to stop

### ISSUE THREAD

**Issue by shkschneider** [marverenic/Jockey#52]
When unpluging the headset while playing.
The music clearly advances at least 1 full second before the player stops (no sound out from the speakers, which is good).
(Nexus 5)

**Comment by marverenic** [comment]
Thanks for pointing this out. Sorry it took so long to respond to, but it's because Jockey was listening for headphone disconnect Intents and ignoring [`AudioManager.ACTION_AUDIO_BECOMING_NOISY`](https://developer.android.com/reference/android/media/AudioManager.html#ACTION_AUDIO_BECOMING_NOISY) Intents. This should be fixed in 72485d7.
