### ISSUE TITLE
Where is DaggerJockeyComponent?

### ISSUE THREAD

**Issue by salvator91** [marverenic/Jockey#63]
Can't find DaggerJockeyComponent referenced in JockeyApplication.

Also, can you please direct me to a tutorial on these new libraries like inject, dagger etc. Changes made in past few weeks are too big for me to follow.

**Comment by marverenic** [comment]
Don't worry, Dagger and RxJava are a lot to take in. Hopefully this should clear some things up:

# Where is `DaggerJockeyComponent`?
`DaggerJockeyComponent` is an automatically generated class built by Dagger at compile time with apt. It contains a ton of boilerplate code to implement the `JockeyComponent` interface.

# [Dagger](http://google.github.io/dagger/)
Dagger is a [dependency injection](https://en.wikipedia.org/wiki/Dependency_injection) library. A dependency is anything that another class needs to work. For example, there are a ton of Activities and Fragments in Jockey that need access to the music library. They don't really care where it comes from or how it works, just that it returns usable data. By using dependency injection, we can abstract the old `Library` class with its static helper methods into a data store object (in this case `MusicStore` and `PlaylistStore`). This allows us to easily swap the data source in the future and to create unit tests for the UI logic (we could accomplish this by changing the component to a fake data source we can test against).

There's a couple of really important interfaces that Dagger uses to get injection working. `JockeyGraph` is a basic interface that tells Dagger what classes it can inject dependencies into. `JockeyGraph` doesn't do anything in and of itself – it's just a convenience interface to make it really easy to make new Components. All of the classes that `JockeyGraph` has `inject()` methods for have protected fields annotated with `@Inject`. They can't be private, because Dagger doesn't use reflection to inject dependencies. When the class has been set up and we call `inject(this)`, all of those fields will be populated by Dependencies from our Component. 

`JockeyComponent` is another interface that extends `JockeyGraph`. `JockeyComponent` is annotated with modules including `ContextModule`, `MediaStoreModule`, and `LastFmModule`, which Dagger uses to figure out how to create the dependencies. When building the project, the Dagger compiler creates a new class, `DaggerJockeyComponent`, that implements `JockeyComponent`. This generated class contains all the code to satisfy dependencies annotated with `@Inject` by implementing all of the `inject()` methods inherited from `JockeyGraph`. Because this class is generated, there's no reflection at runtime, and it's as fast as if you had written the code yourself.

Dagger figures out where to get dependencies from using Modules. Jockey has a few of them as I've mentioned before, but the gist is that they provide instances to Dagger with methods annotated as `@Provides`. We can add the `@Singleton` annotation on top of that to make sure that we only create one instance of any given object. For example, all of Jockey's data stores are annotated as singletons so that we don't waste memory or time generating a new data store every time it's needed in the UI.

# [RxJava](https://github.com/ReactiveX/RxJava/wiki)
RxJava is a Java implementation of the Reactive programming pattern (and people really love explaining it with marble diagrams, which I found pretty unintuitive when learning it for the first time, so I'll avoid them completely here).

In RxJava, everything is based around the `Observable` class. An `Observable` can be thought of as a stream of objects. At any given time, the `Observable` can emit a new item, emit an exception, or complete by terminating the stream. In both the event of an exception or completion, the `Observable` can never emit new items.

To be notified about an `Observable`'s status, you `subscribe` to it with `Observable.subscribe(Subscriber)`, `Observable.subscribe(onNext, onError, onComplete)`, or something similar. Jockey uses the the second method, where each of the parameters is a functional interface (which we can supply using fancy Java 8 [Lambda Expressions](https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html) thanks to Retrolambda). As you may have guessed, any time the original `Observable` gets a new item, our `onNext` callback gets invoked – same thing with `onError` being called when an exception is thrown and `onComplete` when the `Observable` won't be giving us any new items (or when we unsubscribe ourselves).

This is great and all, but why bother? Well, for starters, we can get rid of the gross `Library.OnLibraryChangeListener` callback. If we treat our music library like an `Observable<List<Song>>` (an `Observable` whose object stream comprises of `Song` lists), we'll get new library data as soon as it gets sent to our `Observable`. The other reason that RxJava is used so often is because of multithreading. RxJava can handle passing data between threads with no implementation apart from telling it what threads to use. We can do this by calling `Observable.subscribeOn(Scheduler)` to change what thread the work happens on, and `Observable.observeOn(Scheduler)` to change what thread the results are sent to (which is important since we can only update the UI on the main thread). Jockey doesn't do this yet, but it would be very straightforward to migrate database calls to the `MediaStore` to a background thread in the future.

## RxJava Operators
An operator is a way of changing the object stream produced by an Observable. There's [a ton of these](http://reactivex.io/documentation/operators.html) and I can't even begin to go into detail with all of them, so here's a few of the more common ones: `Observable.map(...)`, `Observable.flatMap(...)`, `Observable.skip(int)`, `Observable.take(int)`, and many others. Notably, `map` and `flatMap` are really flexible and can be hard to differentiate between them, so if you're interested, I recommend a guide called [RxChisel](https://github.com/jingibus/RxChisel) that talks about what [`map`](https://github.com/jingibus/RxChisel/blob/master/Operators/Map.md) and [`flatMap`](https://github.com/jingibus/RxChisel/blob/master/Operators/FlatMap.md) do and gives practical examples of each.

Another important operator is `Observable.compose(...)`. With the help of `RxLifecycle`, we can bind our `Observable` to the corresponding Activity's lifecycle to ensure that the `Subscription` doesn't leak the activity, and that it won't try to do anything dangerous like updating the UI after the activity has been destroyed. This can be done in one line with `Observable.compose(bindToLifecycle())` with no extra work on our part.

## Types of Observables
There's a bunch of basic `Observables` that are included in RxJava. You can make your own, but it's advised against because it's really easy to get wrong, and you can do so much using the tools already at your disposal. The most basic `Observables` can be made with `Observable.empty()`, an `Observable` that calls its subscriber's `onComplete` method as soon as it's subscribed to; `Observable.error(Throwable)`, which calls its subscriber's `onError` method as soon as it's subscribed to, and `Observable.just(Object)`, which calls its subscriber's `onNext` method as soon as it's subscribed to, and then completes itself.

Another powerful kind of `Observable` are `Subjects`. A `Subject` is both a `Subscriber` and an `Observable`. The behavior of a `Subject` depends on which type you use, but right now Jockey only uses the `BehaviorSubject`, which emits the most recent item it has observed and all subsequent observed items to each subscribed `Observer`. Jockey uses `BehaviorSubjects` in `MusicStore` and `PlaylistStore` as a way to keep the most recent library. When the list of all songs, for example, is requested, we can return the corresponding subject so that it can be subscribed to. If we haven't loaded it yet, we can start loading the music library and post the status to the returned `BehaviorSubject` which will update the UI as soon as data is received. If the music library changes for any reason, updates to the `BehaviorSubject` will call the subscriber's `onNext` method, which can go ahead and update the displayed data with no extra work.

---

Hopefully this clears things up. There's a ton of other resources for the two libraries I talked about above, and RxJava especially can be incredibly powerful compared to traditionally firing up an `AsyncTask` or something.

Feel free to post other questions about Jockey related to Dagger or RxJava here, or start a separate thread.
