### ISSUE TITLE
New issue after update

### ISSUE THREAD

**Issue by maysleazy** [marverenic/Jockey#8]
After the service is removed from recent apps, the song pauses.
and when I click play again it randomly plays some song.
Also, cannot remove it from notifications. Works only when the app is in service.
Sorry to say but this version is more broken lol.

**Comment by maysleazy** [comment]
It worked better when I cleared data, but now I cannot remove it from notifications though.
The random song bug was just a weird bug which went away by itself.
Can you just not add a cross (X) mark in the notification to end the service? Just do it like soundcloud does it

**Comment by marverenic** [comment]
Don't feel bad for saying that it's horribly broken, because the reality is that it is :). I've had a Jockey notification for a song that I don't think I've even listened to recently reappear 3 times today after stopping it (and once after rebooting), and that's not okay.

I've reverted the version file and made m18k the default download on SourceForge so that you can downgrade to the previous version without any trouble, although you'll have to uninstall the most recent version first. After seeing how much trouble there's been trying to implement background playing this way, I'm certainly going to change it to a simple close button in the next version. Hopefully I can get that working soon.

Sorry again for causing so much trouble with this version; many mistakes were made.

**Comment by maysleazy** [comment]
I tried working on the close button, its almost the same amount of trouble. Cheers for the try and hardwork though man :) :+1 
I'll try and help as much as possible

**Comment by marverenic** [comment]
I've implemented the close button, and it should be working significantly better than the old method. The downside is that the notification background color is now the default system white on Lollipop since I'm no longer using the MediaStyle for the notification, but I think it still looks nice.

As usual GitHub and SourceForge have been updated, and there's bound to be a few lingering issues.

**Comment by maysleazy** [comment]
I'll test ASAP and report by tomorrow morning :)

**Comment by maysleazy** [comment]
Well the newer issue is, the search doesn't work at all. It crashes when the search is opened

**Comment by nr9992** [comment]
The search works for me on the newer version. Don't know how it is crashing on yours

**Comment by maysleazy** [comment]
Crashed on tabs, works fine after clearing data
