### ISSUE TITLE
Clicking on songs gives MediaPlayer error(-38,0) on occasions

### ISSUE THREAD

**Issue by salvator91** [marverenic/Jockey#92]
Clicking on songs sometimes doesnt play and on debugging it shows error (-38,0) and a message Attempt to call getDuration without a valid mediaplayer

Clicking on it again starts playing. This happens only when I am clicking on songs and not when the player is playing one song after another

Here I found a similar problem. Apparently the start() method is being called before prepareAsync completes its task.
http://stackoverflow.com/questions/18482018/mediaplayer-error-38-0

**Comment by marverenic** [comment]
I've run into this before, but I haven't been able to consistently reproduce it. It definitely needs to get fixed before the next stable release, but it'll probably take a while to figure out what's causing this since it sounds like a race condition.

Let me know if you have more information about how to reproduce this, otherwise I'll try to look into it when I get a chance.

**Comment by salvator91** [comment]
For some reasons frequency has increased. Almost after every 5-7 clicks this is appearing.
I encountered another exception that is dead object exception in the stub proxy.

**Comment by marverenic** [comment]
Jockey has switched to ExoPlayer for media playback as of #146, so this error is no longer possible.
