### ISSUE TITLE
Can't Play song from third party apps .

### ISSUE THREAD

**Issue by iampawan** [marverenic/Jockey#93]

**Comment by marverenic** [comment]
There are two separate issues here, so I've moved the timestamp format into #95.

In regards to playing music from the SD card, this is really hard for me to debug since I don't have a device with an SD card slot, and the mount point for SD cards changes based on what phone you have and how the SD card is set up.

Before I can look into this, I'll need to know what phone you have, what version of Android it's running, and how your SD card is setup (i.e. [Adopted/Non-Adopted storage)](http://www.androidcentral.com/inside-marshmallow-adoptable-storage). It would also help to know the full path to one of the songs that you're trying to play (i.e. `/storage/emulated/sdcard0/Music/Pendulum/Immersion/1-08 - The Island, Pt. 1 (Dawn).mp3`) and if any extra information is being logged to the console (logcat).

**Comment by iampawan** [comment]
Don't worry i will let u know about every detail.

**Comment by iampawan** [comment]
Hi @marverenic i found out the actual problem . The problem is we cant play any song from a third party app / explorer. It says Jockey couldnt fine %s something. Default file manager opens it succesfully. Please have a look .

**Comment by marverenic** [comment]
This should be fixed in #164.
