### ISSUE TITLE
Cant close notification. Add a cancel button plz.

### ISSUE THREAD

**Issue by iampawan** [marverenic/Jockey#94]

**Comment by marverenic** [comment]
In regards to the new notification in Jockey 2.0, the close button was removed because it has essentially been deprecated by Google. To close Jockey now, just swipe the notification away like you would for notifications from other apps after you've paused music and removed Jockey from your recent apps. I'm planning to change this before the next release so that you don't have to remove Jockey from the list of recent apps first.

To elaborate on this, Android 4.4 and lower has a bug where services can't transition between foreground and background states (being in the foreground requires that your notification is ongoing and can't be dismissed normally). Because of this, music players had to include a close button, because there wouldn't be another way to stop the service (and Jockey 2.0 does include a close button when running on such versions of Android).

This was fixed in Android 5.0, though, so Google Play Music and others now use similar behavior to Jockey where stopping the service is done by swiping away the notification. On top of this, Android 5.0 includes `Notification.MediaStyle`, which lets apps build a media control notification without having to create the notification layout themselves. This helps with compatibility since Google can change the music notification style (i.e. like they did in Nougat), and apps don't have to do anything to be using the system notification style. 

To use this on older versions of Android, there's `NotificationCompat.MediaStyle`, which lets developers use the same API on older versions of Android. `NotificationCompat.MediaStyle` includes a `setShowCancelButton()` method, but it's only respected on older versions of Android with the bug that makes ongoing notifications non-dismissable. For apps using `NotificationCompat.MediaStyle`, their only good choice make the notification closeable is to take them out of the foreground and make the notification dismissable.

Because `Notification.MediaStyle` and `NotificationCompat.MediaStyle` use their own layouts, it isn't possible to add a close button in the same way that Jockey did before. It is possible to add a close button to the notification, but then it would appear in the same place as the music control buttons, which isn't ideal because it offsets other buttons and could be pressed accidentally.
