### ISSUE TITLE
Can you also add fastscroller, edit song metadata, delete song , share song and set as ringtone feature?

### ISSUE THREAD

**Issue by iampawan** [marverenic/Jockey#98]
Fast Scroller Link -https://github.com/danoz73/RecyclerViewFastScroller

**Comment by marverenic** [comment]
When making new issues for feature requests, make sure to check that it hasn't been requested before, and try to split up requests like this. Having an issue with multiple feature requests makes it hard to keep track of its status and often leads to it getting lost and forgotten.

Editing a song's metadata has been one of the most requested features for Jockey (#75). I haven't looked into implementation details too much as of right now, so I can't give a very confident status on when that'll be added. It definitely won't be in the next release (2.0), but hopefully can make it in 2.1 or so.

Deleting songs has been suggested before (#14), but was closed in part because the issue contained multiple feature requests. I've gone ahead and made a new issue for song deletions (#99).

Setting a song as the device's ringtone has also come up before in #14. I've created another issue for it (#100), but this is relatively low priority in my opinion, since I don't think many people change their ringtone that often.

Sharing songs has also come up before (#37). This issue also contained several feature requests and has been closed. Implementing this can get a bit tricky since it seems to promote piracy. I'm open to suggestions for how this could be implemented, so feel free to open another issue for this with your opinions.

Fast Scrolling is something that I've also been interested in adding. It was around in some of the earlier builds of Jockey before I transitioned from ListView to RecyclerView, and has mostly just been a matter of finding a good library to do this with. I've moved this into a separate issue (#101) and copied your discussion over.
